export const Colors = {
  CRIMSON: "#D7263D",
  CRIMSON_DARKER: "#d4233b",
  OXFORD_BLUE: "#02182B",
  OXFORD_BLUE_LIGHTER_1: "#02345f",
  OXFORD_BLUE_LIGHTER_2: "#024784",
  SMOOTH_BLUE: "#004e7e",
  SMOOTH_BLUE_DARKER: "#003556",
  BLUE_MUNSELL: "rgb(68, 143, 163)",
  MIDDLE_BLUE: "#68C5DB",
  MIDDLE_BLUE_DARKER: "#4cbfd9",
  WHITE: "#fff",
};

export const ElementColors = {
  BACKGROUND: Colors.OXFORD_BLUE,
  KANBAN_CARD_BG_DARK_MODE: Colors.OXFORD_BLUE_LIGHTER_1,
  KANBAN_CARD_DESCRIPT_BG_DARK_MODE: Colors.OXFORD_BLUE_LIGHTER_2,
  TEXT_DARK_MODE: Colors.WHITE,
  BUTTON_DARK_MODE: Colors.SMOOTH_BLUE,
  BUTTON_CLICK_DARK_MODE: Colors.SMOOTH_BLUE_DARKER,
  BUTTON_TEXT_DARK_MODE: Colors.WHITE,
  LINK_TEXT_DARK_MODE: Colors.MIDDLE_BLUE,
  LINK_TEXT_HOVER_DARK_MODE: Colors.MIDDLE_BLUE_DARKER,
  ERROR_BACKGROUND: Colors.CRIMSON_DARKER,
};

export const Fonts = { FONT_FAMILY: "Work Sans" };
